### ISSUE TITLE
can decompress bvx2 header files?

### ISSUE THREAD

**Issue by startmuscle0731** [ydkhatri/pyliblzfse#1]
I am trying to decompress ipa on Windows.
The json-like data that exists at the top of ipa has been decrypted, but the subsequent files from bvx2 to bvx $ are not decompressed.
Is this library not supported? Also, the bvxn (lzn compress) file could not be decompressed.
Here is the very simple code used for decompression. 

import liblzfse

fw = open('decompressed.dat', 'wb')
with open("testbvx", "rb") as fileread:
	s = fileread.read()
	decrypted_data = liblzfse.decompress(s)
	fw.write(decrypted_data)
	fw.close()

**Comment by ydkhatri** [comment]
If you have can share the sample file, I can take a look at it tomorrow.

**Comment by startmuscle0731** [comment]
thanks reply!
It's a free game, but ipa shouldn't be reprinted by nature, so I sent the download URL to your email address.
I would appreciate it if you could confirm it.

**Comment by ydkhatri** [comment]
I believe the lzfse streams in the .ipa need to be extracted properly first before they can be decompressed. Right now, I don't see the IPA format documented anywhere. I don't believe pulling raw data streams from the file will work.

**Comment by ydkhatri** [comment]
I extracted the first bvx2 stream and tried to debug it, and it get's invalid lzfse status while processing the header chunk itself, which leads me to believe what I just stated above. 
Or Apple's reference implementation just does not work with it, as maybe they changed a few things with lzfse (but this is unlikely).

**Comment by startmuscle0731** [comment]
Thank you for your investigation. No problem, I just saw the information that ipa was compressed with lzfse and thought it could be decompressed. thank you for researching!
