### ISSUE TITLE
About convert liblzfse to png img

### ISSUE THREAD

**Issue by MontaEllis** [ydkhatri/pyliblzfse#2]
Hi!
Now I have some '*.depth' files captured by iphone. All those files are compressed by LZFSE. And 
I succeed to use your lib to decompress those files and get numbers like: '![](https://ellis.oss-cn-beijing.aliyuncs.com/img/20210825213248.png)' 
I wonder if I can transfrom them to '*.png' type. Can you please figure me out?

**Comment by ydkhatri** [comment]
See this:
https://www.swiftforensics.com/2020/07/ktx-to-png-in-python-for-ios-snapshots.html

**Comment by MontaEllis** [comment]
I'm sorry that I can't run your code successfully. Could you do me a favor and transform a '*.depth' file to png type for me? I would send the file to your email.
